spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 78949
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
auth:
  token:
    access:
      expiration: 1000 * 60 * 24
    refresh:
      expiration: 1000 * 60 * 24 * 30
    secret: 0e01a6f5796481fa7afe89f9cf1d6649c86990a1d9b6a0026d1bad0fe947c1bb